# NUMPY BASICS

In [1]:
import numpy as np

In [2]:
print("hello world")

hello world


In [3]:
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [7]:
b= np.array([[1,2],[3,4]])

In [9]:
print(b)

[[1 2]
 [3 4]]


In [19]:
# GET DIMENSIONS
b.ndim

2

In [20]:
# Get Shape
b.shape

(2, 2)

In [21]:
a.shape

(3,)

In [31]:
# Control Datatype
c=np.array([1,2,3], dtype='int64')
c

array([1, 2, 3], dtype=int64)

In [33]:
# Get DAtatype
c.dtype

dtype('int64')

In [32]:
# getsize *item*
c.itemsize

8

In [34]:
#  Get total size
# 3 elements * 8 bytes = 24
c.nbytes

24

## Acessing/Changing certain rows,columns,elements etc. ##

In [45]:
# getting a specific element [r,c]
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
d[1,2]

10

In [47]:
#getting a specific row [r,:]
d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
# getting a specific column [:,c]
d[:,1]

array([2, 9])

In [53]:
# getting more fancier (getting elemmnts between specific indexes and with specific skip)(startindex:endindex:elementskipdistance)
d[1,2:6:2]

array([10, 12])

In [64]:
# changing elements
d[1,2]=20
print(d)
# changing whole row or column
d[1,:]=[7,6,5,4,3,2,1]
print(d)

[[ 1  2  1  4  5  6  7]
 [ 8  9 20 11 12 13 14]]
[[1 2 1 4 5 6 7]
 [7 6 5 4 3 2 1]]


# 3D EXAMPLE #

In [67]:
a=np.array([[[1,2],[4,5]],[[7,8],[9,10]]])
print(a)

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]]


In [68]:
# getting a specific element (work inside out)
# for let's say getting no. 5

a[0,1,1]



5

In [70]:
#experimenting
a[:,:,1]

array([[ 2,  5],
       [ 8, 10]])

In [74]:
# replacing values
a[:,1,:1]=[[10],[11]]
print(a)

[[[ 1  2]
  [10 10]]

 [[ 7  8]
  [11 10]]]


## Initializing different types of arrays ##

In [79]:
# All 0's
x=np.zeros((3,3))
x


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
# all ones, (can still change datatype)
x=np.ones((2,2), dtype='int64')
x

array([[1, 1],
       [1, 1]], dtype=int64)

In [82]:
# any other number ((rows,columns),number)
x=np.full((3,3),5)
x

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [84]:
# shape like any other exisiting array
x=np.full_like(a,7)
x

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [90]:
#  random DECIMAL numbers (shape without parenthesis)
x=np.random.rand(4,4)
x

array([[0.36154554, 0.92757006, 0.59214671, 0.94446378],
       [0.87015667, 0.2846752 , 0.61618193, 0.22661089],
       [0.95471222, 0.3965208 , 0.54305181, 0.27078641],
       [0.35325645, 0.19779612, 0.13971217, 0.1811245 ]])

In [92]:
# RANDOM BUT SHAPE SAME AS EXISTING ONE *RANDOM_SAMPLE*
x=np.random.random_sample(a.shape)
x

array([[[0.89572145, 0.08508126],
        [0.72306401, 0.97425401]],

       [[0.39099705, 0.31279852],
        [0.4933568 , 0.21259365]]])

In [93]:
x.shape

(2, 2, 2)

In [94]:
x.nbytes

64

In [103]:
# random INT value ( max value,size=(rows,columns))
x=np.random.randint(10, size=(3,3))
x

array([[7, 3, 0],
       [7, 6, 2],
       [4, 1, 7]])

In [108]:
#  identity matrix
x=np.identity((3))
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## TASK: BUILDING A MATRIX OF 5X5 WITH ALL BORDERS=1, CENTRE=9 THE REST=0


In [112]:
t1=np.ones((5,5))
t1[1:4,1:4]=0
t1[2,2]=9

t1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
# or
t1=np.ones((5,5))
thelp=np.zeros((3,3))
thelp[1,1]=9
t1[1:-1,1:-1]=thelp
t1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### BE CAREFULL WHILE COPYING ARRAYS

In [119]:
a=np.random.randint(7,size=(2,2))
print(a)
b=a
b[0,1]=20
print(b)
print(a)
# the value changes for a too!!!!

[[6 6]
 [1 0]]
[[ 6 20]
 [ 1  0]]
[[ 6 20]
 [ 1  0]]


In [120]:
# use copy 
print(a)
b=a.copy()
b[1,1]=99
print(b)
print(a)
# value saved

[[ 6 20]
 [ 1  0]]
[[ 6 20]
 [ 1 99]]
[[ 6 20]
 [ 1  0]]


## Mathematics

In [121]:
a=np.array([[1,2],[2,1]])
a

array([[1, 2],
       [2, 1]])

In [122]:
a+2

array([[3, 4],
       [4, 3]])

In [123]:
a-2

array([[-1,  0],
       [ 0, -1]])

In [124]:
a*2

array([[2, 4],
       [4, 2]])

In [126]:
a/2

array([[0.5, 1. ],
       [1. , 0.5]])

In [133]:
# to increment power
a**2


array([[1, 4],
       [4, 1]])

In [134]:
b=np.array([[6,6],[6,6]])
a+b

array([[7, 8],
       [8, 7]])

In [130]:
a*b #does scalar multiplication

array([[ 6, 12],
       [12,  6]])

In [135]:
# to find sin
np.sin(a)

array([[0.84147098, 0.90929743],
       [0.90929743, 0.84147098]])

## Linear Algebra

In [137]:
a=np.full((2,2),5)
print(a)

b=np.full((2,3),2)
print(b)

[[5 5]
 [5 5]]
[[2 2 2]
 [2 2 2]]


In [138]:
# to multiply
np.matmul(a,b)

array([[20, 20, 20],
       [20, 20, 20]])

In [141]:
# to find determinent
c=np.full((4,4),5)
np.linalg.det(c)


0.0

In [142]:
# can also find 
# inverse
# trace
# eigen vectors and values
# singular vector decomposition
# matrix norm
# etc

### STATISTICS

In [151]:
stat=np.array([[1,2,3],[4,5,6],[7,8,9]])
stat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
np.min(stat)

1

In [150]:
np.max(stat,axis=1)

array([20,  6,  9])

In [153]:
np.sum(stat)

45

## reorganising arrays

In [160]:
a= np.ones((1,10))
b= a.reshape((5,2))
b
# total no. of elements need to same

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [165]:
# vertically stacking
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])
# shape needs to be same


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [166]:
#  horizontally stacking
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

## Miscellaneous Things


#### load data from a file

In [170]:
file_data= np.genfromtxt('data.txt', delimiter=',')#delimitters are separation
file_data.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean Masking and Advanced Indexing

In [178]:
file_data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [179]:
a=file_data[file_data > 50]
a

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [180]:
a.astype('int32')

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [182]:
# can be indexed thru an array
a=np.array([1,2,3,4,5,6,7])
a[[1,2,5]]

array([2, 3, 6])

In [185]:
# ANY data =.....
np.any( file_data > 50)
# any data =..... for all columns
np.any( file_data > 50, axis=0)
# here these true false indexes refer to the column's index

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [186]:
# ALL data =.....
np.all( file_data > 50)
# ALL data =..... for all columns
np.all( file_data > 50, axis=0)
# here these true false indexes refer to the column's index

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [187]:
((file_data <20) & (file_data >10)) 

array([[False,  True, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True],
       [False, False, False,  True, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [190]:
~((file_data <20) & (file_data >10))

array([[ True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False, False],
       [ True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

## TASK 2

In [191]:
t2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
t2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [194]:
# to access 11,12,16,17
t2[2:4 , 0:2]

array([[11, 12],
       [16, 17]])

In [196]:
# to access 2,8,14,20
t2[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [201]:
# to access 4,5,24,25,29,30
t2[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

## ENDS